### PR TITLE
Fixed second calculation and added options.

### LINKED ISSUE #16: pisound-btn tick to seconds conversion returns the wrong value for even tick counts
the macro TICK_2_SECONDS return one value too high if the last character is divisible by 2.

In addition, there should be options to specify all the seconds for hold (not just the odd ones) and align them at the second change or half way between the second changes.

### PR DESCRIPTION
**Pull request by Claudenw**
Added --full-time to include even seconds as well
Added --offset-time to offset the second changes by 1/2 second
Added --time-help to display help with the new time options.

Did not change the default operation.

closes #16

### CODE REVIEW

**Comment by gtrainavicius** [comment]
Hey, thank you for the pull request. I've looked into it, as well as an older version of the code, and found that the minimum hold time reported was 1s, not 3s:

https://github.com/BlokasLabs/pisound/blob/25d8835d019bc9a073e1a227a63859102ef16c7a/pisound-btn/pisound-btn.c#L270

The minimum hold time was 400ms.

So it should call HOLD_1S script when the button was held within [0.4; 3)
HOLD_3S script when held within [3; 5)
HOLD_5S script when held within [5; 7)
HOLD_OTHER for any longer holds.

Btw, every HOLD script gets called with the milliseconds held as the 2nd argument, so HOLD_1S, HOLD_3S, HOLD_5S, HOLD_OTHER could point to the same single script that would just receive the milliseconds and could do hold-time based logic on its own according to its needs, this way it'd be possible to decouple the time tracking rules from pisound-btn to the script(s) that get called.

Btw, you've added a rule to build 'test.c', but haven't added the test.c file itself.

**Comment by Claudenw** [comment]
Fixed the errors noted above and updated the timing documentation to match.

Added test.c which will print a table of expected results at various inflection points.

**Comment by Claudenw** [comment]
@gtrainavicius  The code should be fixed now.

**Comment by gtrainavicius** [comment]
Thank you, everything seems to be alright. :) I've released updated pisound-btn package, version 1.14-1.

**Pull request merged**
